const homePlaces = [
  {
    id: "place1",
    img1: "/assets/place1.png",
    paragraph1: "Desert King",
    paragraph2: "2345km away",
    paragraph3: "1MBT per night",
    paragraph4: "available for 2weeks stay",
  },
  {
    id: "place2",
    img1: "/assets/place2.png",
    paragraph1: "Desert King",
    paragraph2: "2345km away",
    paragraph3: "1MBT per night",
    paragraph4: "available for 2weeks stay",
  },
  {
    id: "place3",
    img1: "/assets/place3.png",
    paragraph1: "Desert King",
    paragraph2: "2345km away",
    paragraph3: "1MBT per night",
    paragraph4: "available for 2weeks stay",
  },
  {
    id: "place4",
    img1: "/assets/place4.png",
    paragraph1: "Desert King",
    paragraph2: "2345km away",
    paragraph3: "1MBT per night",
    paragraph4: "available for 2weeks stay",
  },
  {
    id: "place5",
    img1: "/assets/place5.png",
    paragraph1: "Desert King",
    paragraph2: "2345km away",
    paragraph3: "1MBT per night",
    paragraph4: "available for 2weeks stay",
  },
  {
    id: "place6",
    img1: "/assets/place6.png",
    paragraph1: "Desert King",
    paragraph2: "2345km away",
    paragraph3: "1MBT per night",
    paragraph4: "available for 2weeks stay",
  },
  {
    id: "place7",
    img1: "/assets/place7.png",
    paragraph1: "Desert King",
    paragraph2: "2345km away",
    paragraph3: "1MBT per night",
    paragraph4: "available for 2weeks stay",
  },
  {
    id: "place8",
    img1: "/assets/place8.png",
    paragraph1: "Desert King",
    paragraph2: "2345km away",
    paragraph3: "1MBT per night",
    paragraph4: "available for 2weeks stay",
  },
];

// Places Data
export const places = [
  {
    id: "place1",
    img1: "/assets/place5.png",
    paragraph1: "Desert King",
    paragraph2: "2345km away",
    paragraph3: "1MBT per night",
    paragraph4: "available for 2weeks stay",
  },
  {
    id: "place2",
    img1: "/assets/place6.png",
    paragraph1: "Desert King",
    paragraph2: "2345km away",
    paragraph3: "1MBT per night",
    paragraph4: "available for 2weeks stay",
  },
  {
    id: "place3",
    img1: "/assets/place7.png",
    paragraph1: "Desert King",
    paragraph2: "2345km away",
    paragraph3: "1MBT per night",
    paragraph4: "available for 2weeks stay",
  },
  {
    id: "place4",
    img1: "/assets/place8.png",
    paragraph1: "Desert King",
    paragraph2: "2345km away",
    paragraph3: "1MBT per night",
    paragraph4: "available for 2weeks stay",
  },
  {
    id: "place5",
    img1: "/assets/place1.png",
    paragraph1: "Desert King",
    paragraph2: "2345km away",
    paragraph3: "1MBT per night",
    paragraph4: "available for 2weeks stay",
  },
  {
    id: "place6",
    img1: "/assets/place2.png",
    paragraph1: "Desert King",
    paragraph2: "2345km away",
    paragraph3: "1MBT per night",
    paragraph4: "available for 2weeks stay",
  },
  {
    id: "place7",
    img1: "/assets/place3.png",
    paragraph1: "Desert King",
    paragraph2: "2345km away",
    paragraph3: "1MBT per night",
    paragraph4: "available for 2weeks stay",
  },
  {
    id: "place8",
    img1: "/assets/place4.png",
    paragraph1: "Desert King",
    paragraph2: "2345km away",
    paragraph3: "1MBT per night",
    paragraph4: "available for 2weeks stay",
  },
  {
    id: "place9",
    img1: "/assets/home3.png",
    paragraph1: "Desert King",
    paragraph2: "2345km away",
    paragraph3: "1MBT per night",
    paragraph4: "available for 2weeks stay",
  },
  {
    id: "place10",
    img1: "/assets/home4.png",
    paragraph1: "Desert King",
    paragraph2: "2345km away",
    paragraph3: "1MBT per night",
    paragraph4: "available for 2weeks stay",
  },
  {
    id: "place11",
    img1: "/assets/place9.png",
    paragraph1: "Desert King",
    paragraph2: "2345km away",
    paragraph3: "1MBT per night",
    paragraph4: "available for 2weeks stay",
  },
  {
    id: "place12",
    img1: "/assets/place10.png",
    paragraph1: "Desert King",
    paragraph2: "2345km away",
    paragraph3: "1MBT per night",
    paragraph4: "available for 2weeks stay",
  },
  {
    id: "place13",
    img1: "/assets/place11.png",
    paragraph1: "Desert King",
    paragraph2: "2345km away",
    paragraph3: "1MBT per night",
    paragraph4: "available for 2weeks stay",
  },
  {
    id: "place14",
    img1: "/assets/place12.png",
    paragraph1: "Desert King",
    paragraph2: "2345km away",
    paragraph3: "1MBT per night",
    paragraph4: "available for 2weeks stay",
  },
  {
    id: "place15",
    img1: "/assets/place13.png",
    paragraph1: "Desert King",
    paragraph2: "2345km away",
    paragraph3: "1MBT per night",
    paragraph4: "available for 2weeks stay",
  },
  {
    id: "place16",
    img1: "/assets/home2.png",
    paragraph1: "Desert King",
    paragraph2: "2345km away",
    paragraph3: "1MBT per night",
    paragraph4: "available for 2weeks stay",
  },
];

export const stars = [
  "/assets/star.png",
  "/assets/star.png",
  "/assets/star.png",
  "/assets/star.png",
  "/assets/star.png",
];

// Links

export const links = [
  {
    id: "home",
    content: "Home",
    to: "/",
  },
  {
    id: "places",
    content: "Place to stay",
    to: "/places",
  },
  {
    id: "nft",
    content: "NFTs",
    to: "/",
  },
  {
    id: "community",
    content: "Community",
    to: "/",
  },
];

export default homePlaces;
